// Replanning: decides WHEN a status change needs a replan and re-distributes the remaining
// topics over the remaining days by reusing scheduler.js (there is no second algorithm).
const Topic = require('../model/topicSchema');
const ScheduleDay = require('../model/scheduleDaySchema');
const { scheduleTopics, startOfUtcDay } = require('./agents/scheduler');

const DAY_MS = 24 * 60 * 60 * 1000;
const EPS = 1e-9;
const round = (hours) => Math.round(hours * 1000) / 1000;
const dateLabel = (ms) => new Date(ms).toISOString().slice(0, 10);
const NOT_SCHEDULED = 'not scheduled';

/**
 * Should changing a topic's status trigger a replan?
 *   missed                              -> yes
 *   done, more than 1 day away from the
 *   topic's (last) scheduled day        -> yes ("early" or "late")
 *   reopened (done -> pending)          -> yes, so the topic gets a slot again
 *   anything else, or no schedule yet   -> no
 * Returns { trigger, daysOffset } or null. `today` is a UTC-midnight Date.
 */
function decideReplan({ oldStatus, newStatus, slotDates, hasSchedule, today }) {
  if (!hasSchedule || oldStatus === newStatus) return null;
  if (newStatus === 'missed') return { trigger: 'missed', daysOffset: null };
  if (newStatus === 'pending') return oldStatus === 'done' ? { trigger: 'reopened', daysOffset: null } : null;

  // newStatus === 'done'
  if (slotDates.length === 0) return null; // never scheduled: nothing to compare against
  const dueMs = Math.max(...slotDates.map((d) => startOfUtcDay(d).getTime()));
  const diff = Math.round((today.getTime() - dueMs) / DAY_MS); // > 0: finished late, < 0: early
  if (Math.abs(diff) <= 1) return null;
  return diff > 0 ? { trigger: 'done_late', daysOffset: diff } : { trigger: 'done_early', daysOffset: -diff };
}

// A schedule day is "completed" when every topic planned on it is done.
async function syncDayCompletion(planId) {
  const [topics, days] = await Promise.all([Topic.find({ planId }), ScheduleDay.find({ planId })]);
  const doneIds = new Set(topics.filter((t) => t.status === 'done').map((t) => t._id.toString()));
  const ops = days
    .filter((d) => d.slots.length > 0 && d.slots.every((s) => doneIds.has(s.topicId.toString())) !== d.completed)
    .map((d) => ({ updateOne: { filter: { _id: d._id }, update: { $set: { completed: !d.completed } } } }));
  if (ops.length) await ScheduleDay.bulkWrite(ops);
}

/**
 * Re-distributes every topic that is not done over tomorrow .. (exam - 1).
 *   - past days:   keep only work that is done (history); undone slots are removed
 *   - today:       left as planned, except slots of topics that were just marked missed
 *   - later days:  wiped and regenerated by the scheduler
 * A pending topic that already has hours planned today only has its REMAINING hours rescheduled.
 * Returns facts about what happened (used for the warning and the explanation).
 */
async function replanRemaining(plan, now = new Date()) {
  const today = startOfUtcDay(now);
  const todayMs = today.getTime();
  const tomorrow = new Date(todayMs + DAY_MS);

  const [topics, days] = await Promise.all([
    Topic.find({ planId: plan._id }).sort({ _id: 1 }),
    ScheduleDay.find({ planId: plan._id }),
  ]);
  const todo = topics.filter((t) => t.status !== 'done');
  const todoIds = new Set(todo.map((t) => t._id.toString()));
  const missedIds = new Set(todo.filter((t) => t.status === 'missed').map((t) => t._id.toString()));

  const oldFirstMs = new Map(); // topicId -> earliest planned day (for the "moves" report)
  const hoursToday = new Map(); // topicId -> hours already planned for today
  for (const day of days) {
    const ms = startOfUtcDay(day.date).getTime();
    for (const slot of day.slots) {
      const id = slot.topicId.toString();
      if (!oldFirstMs.has(id) || ms < oldFirstMs.get(id)) oldFirstMs.set(id, ms);
      if (ms === todayMs) hoursToday.set(id, (hoursToday.get(id) || 0) + slot.hours);
    }
  }

  const toSchedule = [];
  for (const topic of todo) {
    if (topic.difficulty == null || topic.estHours == null) continue;
    const keptToday = topic.status === 'pending' ? hoursToday.get(topic._id.toString()) || 0 : 0;
    const remaining = round(topic.estHours - keptToday);
    if (remaining > EPS) toSchedule.push({ id: topic._id, difficulty: topic.difficulty, estHours: remaining });
  }

  // Trim the existing schedule.
  const ops = [];
  for (const day of days) {
    const ms = startOfUtcDay(day.date).getTime();
    if (ms > todayMs) {
      ops.push({ deleteOne: { filter: { _id: day._id } } });
      continue;
    }
    const drop = ms < todayMs ? todoIds : missedIds;
    const kept = day.slots.filter((s) => !drop.has(s.topicId.toString()));
    if (kept.length === day.slots.length) continue;
    if (kept.length === 0) {
      ops.push({ deleteOne: { filter: { _id: day._id } } });
    } else {
      ops.push({
        updateOne: {
          filter: { _id: day._id },
          update: {
            $set: {
              slots: kept.map((s) => ({ topicId: s.topicId, hours: s.hours })),
              topicIds: kept.map((s) => s.topicId),
            },
          },
        },
      });
    }
  }

  let result;
  try {
    result = scheduleTopics(toSchedule, plan.examDate, plan.dailyHours, tomorrow);
  } catch (err) {
    if (!(err instanceof RangeError)) throw err;
    // Exam is tomorrow or earlier: no study days remain after today.
    result = {
      days: [],
      unscheduled: toSchedule.map((t) => ({ topicId: t.id, hours: t.estHours })),
      warning: toSchedule.length
        ? `There are no study days left before the exam, so ${toSchedule.length} topic${toSchedule.length === 1 ? '' : 's'} could not be scheduled.`
        : null,
      availableDays: 0,
    };
  }

  if (ops.length) await ScheduleDay.bulkWrite(ops);
  if (result.days.length) {
    await ScheduleDay.insertMany(
      result.days.map((d) => ({ planId: plan._id, date: d.date, topicIds: d.topicIds, slots: d.slots }))
    );
  }
  await syncDayCompletion(plan._id);

  // Which topics actually moved (first planned day changed)?
  const newFirstMs = new Map();
  for (const day of result.days) {
    for (const slot of day.slots) {
      const id = slot.topicId.toString();
      if (!newFirstMs.has(id) || day.date.getTime() < newFirstMs.get(id)) newFirstMs.set(id, day.date.getTime());
    }
  }
  const nameById = new Map(topics.map((t) => [t._id.toString(), t.name]));
  const moves = [];
  for (const { id } of toSchedule) {
    const key = id.toString();
    const from = oldFirstMs.has(key) ? dateLabel(oldFirstMs.get(key)) : NOT_SCHEDULED;
    const to = newFirstMs.has(key) ? dateLabel(newFirstMs.get(key)) : NOT_SCHEDULED;
    if (from !== to) moves.push({ topic: nameById.get(key), from, to });
  }

  return {
    warning: result.warning,
    unscheduledTopicIds: result.unscheduled.map((u) => u.topicId),
    rescheduledTopics: toSchedule.length,
    daysLeft: result.availableDays,
    moves: moves.slice(0, 6),
  };
}

module.exports = { decideReplan, replanRemaining, syncDayCompletion };
